config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
  get "notes/rss"
  resources :notes, only: [:show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ContentfulModel::Base
  self.content_type_id = "article"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    @notes = Article.all.order(publish_date: :desc).load
  end

  def show
    @note = Article.find_by(slug: params[:id]).load.first
  end

  def rss
    @notes = Article.all.order(publish_date: :desc).load
    render 'rss', content_type: 'text/xml', formats: :xml
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @articles = Article.all.order(publish_date: :desc).limit(5).load
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
  def markdown_renderer
    Redcarpet::Render::HTML.new({ with_toc_data: true })
  end

  def markdown
    Redcarpet::Markdown.new(markdown_renderer,
      {fenced_code_blocks: true}
    )
  end

  def toc_renderer
    Redcarpet::Markdown.new(
      Redcarpet::Render::HTML_TOC
    )
  end

  def show_contents?
    word_count > 1000 && table_of_contents.strip.present?
  end

  def rendered_body
    markdown.render(@note.body).html_safe
  end

  def word_count
    rendered_body.split(' ').count
  end

  def table_of_contents
    toc_renderer.render(@note.body).html_safe
  end

  def publish_date
    @note.publish_date.strftime("%B %Y")
  end

  def cdata(content)
    ('<![CDATA[ ' + content + ' ]]>').html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <% if ENV['GOOGLE_ANALYTICS'] == 'enabled' %>
      <%= render 'shared/google_analytics' %>
    <% end %>
    <title>Najaf Ali's Homepage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/base16/ashes.min.css" integrity="sha512-KX15mI6Sw0VzQyAOf4MAPS9BZ0tWXyZrGPHKSkqDmy40Jl+79f8ltpj6FvLJ+3obnH56ww0ukclsd6xGAxb5mA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/highlight.min.js" integrity="sha512-rdhY3cbXURo13l/WU9VlaRyaIYeJ/KBakckXIvJNAQde8DgpOmE+eZf7ha4vdqVjTtwQt69bD2wH2LXob/LB7Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/languages/ruby.min.js" integrity="sha512-CodtXF69yrF+WC9mdciInVG1X0GeAaZrjjNB+gaEmVsyUn3YR7yfSHad1Q+SwDAfivwmUDo8qTlaUUCtlbLeMg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>hljs.highlightAll();</script>



    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/notes/index.html.erb
<article>
  <section>
    &nbsp;
    <%= render 'shared/nav' %>
  </section>
  <h1>All the notes</h1>
  <ul>
    <% @notes.each do |note| %>
      <li>
        <%= link_to note.title, note_path(note.slug) %>
      </li>
    <% end %>
  </ul>
</article>

app/views/notes/rss.xml.erb
<rss xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:media="http://search.yahoo.com/mrss/" version="2.0">
  <channel>
    <title>
      <%=cdata('Ali writing things')%>
    </title>
    <description>
      <%=cdata "Ali's place for writing about things on the internet"%>
    </description>
    <link href="https://najafali.blog/notes/rss/" rel="self" type="application/rss+xml" />
  <% @notes.each do |note| %>
    <item>
      <title><%= cdata note.title %></title>
      <link>https://najafali.blog/notes/<%= note.slug %></link>
      <author><%= cdata 'Najaf Ali' %></author>
      <description>
        <%= cdata markdown.render(note.body).html_safe %>
      </description>
    </item>
  <% end %>
  </channel
</rss>

app/views/notes/show.html.erb
<article>
  <section>
    &nbsp;
    <%= render 'shared/nav' %>
  </section>
  <h2 class='note-title'><%= @note.title %></h2>

  <div class='microtext'>
    <%= publish_date %>,
    <%= word_count %> words
  </div>

  <section>
    <% if show_contents? %>
      <h3>Contents</h3>
        <%= table_of_contents %>
      <hr />
    <% end %>
    <%= rendered_body %>
  </section>
</article>

app/views/pages/home.html.erb
<article>
<h1>Najaf Ali's Homepage</h1>

  <section>
  <%= render 'shared/nav' %>

  <p>👋🏾 I'm a British immigrant to Japan. I live in Japan because I like it here more than anywhere else.</p>

  <!--<p>I speak fluent Japanese, well enough that my code switch is fast and easy, and I can use circumlocution and other tactics to survive in any conversation. I learned Japanese primarily by drinking with Japanese people. I try to cook but mostly end up eating out, so probably know Sendai's restaurants better than most natives here.</p>-->

  <p>I was born in the UK and moved around to a number of different countries, before graduating and going to Japan for the first time on the JET programme in 2006. After a ten year break in the UK where I founded a software development consultancy and had a couple of children, I moved back to Japan in August 2018.</p>


  <h2>📝 Notes</h2>

  <p>Here are some things I wrote recently:</p>

  <ul>
    <% @articles.each do |article| %>
      <li>
        <%= link_to article.title, note_path(article.slug), style: 'text-decoration: none' %>
      </li>
    <% end %>
  </ul>

  <p>
  See <%= link_to "a big list of all the notes", notes_path %>
  </p>
  </section>
</article>

app/views/shared/_google_analytics.html.erb
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-FRK0NVNJDK"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-FRK0NVNJDK');
</script>

app/views/shared/_nav.html.erb
<nav>
  <a href='/notes'>Articles</a>
  /
  <a href='https://github.com/Najaf'>GitHub</a>
  /
  <a href='https://twitter.com/alinajaf'>Twitter</a>
  /
  <a href='https://www.linkedin.com/in/najafali/'>LinkedIn</a>
  /
  <a href='https://strongwordsbyali.substack.com/'>Substack</a>
</nav>